# Generated by Django 6.0.4 on 2026-07-01 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mercadopago', 'MercadoPago'), ('webpay', 'Webpay Plus')], default='mercadopago', max_length=20)),
                ('mercadopago_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('preference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('token_webpay', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('monto', models.DecimalField(decimal_places=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En proceso')], default='pendiente', max_length=20)),
                ('metodo', models.CharField(blank=True, max_length=50, null=True)),
                ('auditado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
