# Generated by Django 6.0.4 on 2026-07-01 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pago_confirmado', 'Pago confirmado'), ('en_preparacion', 'En preparación'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente_pago', max_length=30)),
                ('urgencia', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('tipo_despacho', models.CharField(choices=[('express', 'Express'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('costo_envio', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=0, max_digits=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('aprobada_por_ejecutivo', models.BooleanField(default=False)),
                ('tracking_simulado', models.CharField(blank=True, max_length=50, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_orden', to='productos.producto')),
            ],
        ),
    ]
